global using System.Collections.Generic;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using Survivor.Enums;
global using Survivor.Managers;
global using Survivor.PlayerObjects;
global using Texture2D = Microsoft.Xna.Framework.Graphics.Texture2D;
global using Survivor.Controller;
global using Microsoft.Xna.Framework.Content;
global using System.Threading;
global using System.Windows.Forms.VisualStyles;
global using Survivor.Enemy;
global using System.Timers;
global using Timer = System.Timers.Timer;
global using System;
global using Survivor.Base;
global using Survivor.Objects;
global using Survivor.Drawers;
global using Survivor.Backgrounds;
global using System.Linq;